### ISSUE TITLE
Get the best policy

### ISSUE THREAD

**Issue by serteckian** [matthiasplappert/keras-rl#49]
Hi, after training is done, I can test the actor corresponding with the last policy. 
However, I am observing that the episode-reward for some intermediate steps is **much** better than the policy at the last stage of the training phase. 
I will go on and tuning the parameters (and debugging my environment) but, just in case, is it possible to track and store the **best** policy that has provided the highest max-value during the training phase (kind of earlier stopping)?
Thanks!

**Comment by matthiasplappert** [comment]
What I usually do is the following: Use `FileLogger` and `ModelIntervalCheckpoint` together to periodically write out your model weights as well as statistics. You can then either select the best weights by looking at the stats or you evaluate each weight checkpoint and select the best. The `dqn_atari.py` example uses both callbacks, so that's a good starting point.

I plan to improve this in the future e.g. by periodically evaluating the agent (something that is currently not implemented), but for now that should still work for what you want.

**Comment by RyanHope** [comment]
There is the 'EarlyStopping' callback in Keras https://github.com/fchollet/keras/blob/master/keras/callbacks.py#L313

**Comment by serteckian** [comment]
Yeah! This is a useful workaround for my purpose.  Really, thank you very much for your support!

**Comment by RyanHope** [comment]
There is a pending PR that will expose the last info passed from the env to the end of episode callback. This will allow env stats and model metrics to be logged in a single file.
