### ISSUE TITLE
adapting ddpg agent for the Atari environment

### ISSUE THREAD

**Issue by small-yellow-duck** [matthiasplappert/keras-rl#62]
I'd like to adapt the ddpg agent for environments other than Pendulum-v0. One problem is that the environment action is Discrete(6) for the Atari environment but a numpy array for the Pendulum-v0 environment. Is there a way to avoid statements which use the shape of the action variable?

ie

  File "/lib/python2.7/site-packages/keras_rl-0.2.0rc1-py2.7.egg/rl/agents/ddpg.py", line 222, in select_action
    assert noise.shape == action.shape

**Comment by bstriner** [comment]
You could reuse some of the code from this PR: https://github.com/openai/gym/pull/451

The code flattens arbitrary spaces into single vectors.

You would still have to write custom code for searching, because searching a discreet space is different than searching a continuous space. However, you should be able to use that PR to write the same model for any spaces.

Cheers,
Ben
