### ISSUE TITLE
Installation with pip

### ISSUE THREAD

**Issue by lemonzi** [matthiasplappert/keras-rl#64]
Running `pip search keras-rl` suggests that the package is pip-installable, but when I try to do it I get a "No matching distribution found" error. Is it supposed to work? If not, it would be very convenient.

**Comment by bstriner** [comment]
No matching distribution should mean the package is available but not for your system. What OS and version of python?

**Comment by lemonzi** [comment]
Oh! I didn't see any restrictions in `setup.py`, and I run on Python 2.7 as indicated in the readme. My OS is OSX 10.10.

**Comment by lemonzi** [comment]
Since the only release is a release candidate, I though it could be that the `--pre` switch is needed, but I tried it and it didn't work either. Anyway, as there have been significant changes since then I've installed form head with `pip install git+https://github.com/matthiasplappert/keras-rl`, and the installation went fine.

**Comment by bstriner** [comment]
It wouldn't be an issue with `setup.py`. When you upload to PyPI, you have a lot of choices of what to build and upload, and maybe the upload didn't have a universal wheel.

I uploaded some packages not too long ago. If you look at the bottom, you'll see the list of files includes a universal wheel and a source distribution.
https://pypi.python.org/pypi/keras-adversarial/0.0.3
https://pypi.python.org/pypi/keras-tqdm/1.0.7

Whereas in keras-rl, I don't see those files listed.
https://pypi.python.org/pypi/keras-rl/0.1

My guess is the build wasn't fully uploaded to PyPI. I assume the PyPI version will be fixed as the project progresses. Probably better to use the development version for now since there are a lot of updates.

**Comment by lemonzi** [comment]
I see! So there's an entry, but nothing uploaded. Well, it makes sense to use the development version, yes. I'll stick to the git installation. Thanks!

**Comment by matthiasplappert** [comment]
I've just published version 0.2.0 to pypi: https://pypi.python.org/pypi/keras-rl/0.2.0

You can now use `pip install keras-rl` to install the package.
